// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persontec.Api.Data;

namespace Persontec.Api.Migrations
{
    [DbContext(typeof(HrContext))]
    [Migration("20200212160013_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Persontec.Api.Data.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("SupervisorEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("SupervisorEmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeNumber = 101,
                            FirstName = "Dennis",
                            LastName = "Dunaway"
                        });
                });

            modelBuilder.Entity("Persontec.Api.Data.Entities.EmploymentPeriod", b =>
                {
                    b.Property<int>("EmploymentPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("EmploymentPeriodId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmploymentPeriod");

                    b.HasData(
                        new
                        {
                            EmploymentPeriodId = 1,
                            EmployeeId = 1,
                            EndingDate = new DateTime(2020, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Persontec.Api.Data.Entities.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrganizationCode")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("VicePresidentId")
                        .HasColumnType("int");

                    b.HasKey("OrganizationId");

                    b.HasIndex("VicePresidentId")
                        .IsUnique();

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationId = 1,
                            OrganizationCode = 12345,
                            OrganizationName = "Group J",
                            VicePresidentId = 1
                        });
                });

            modelBuilder.Entity("Persontec.Api.Data.Entities.Employee", b =>
                {
                    b.HasOne("Persontec.Api.Data.Entities.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorEmployeeId");
                });

            modelBuilder.Entity("Persontec.Api.Data.Entities.EmploymentPeriod", b =>
                {
                    b.HasOne("Persontec.Api.Data.Entities.Employee", null)
                        .WithMany("EmploymentPeriods")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Persontec.Api.Data.Entities.Organization", b =>
                {
                    b.HasOne("Persontec.Api.Data.Entities.Employee", "VicePresident")
                        .WithOne("Organization")
                        .HasForeignKey("Persontec.Api.Data.Entities.Organization", "VicePresidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
